color = true
color-match = "3;4;93"
group = true
column = false
after = 0
before = 0
context = 0
files-with-matches = false
count = false
e = false
ignore-case = false
smart-case = true
word-regexp = false
ignore = "_worktree"
vcs-ignore = ".gitignore"
global-gitignore = "~/.gitignore-global"
home-ptignore = "~/.ptignore"
skip-vcs-ignores = false
depth = 25
follow = false
hidden = true
