[[plugins]]
repo     = 'Shougo/denite.nvim'
#repo     = 'delphinus/denite.nvim'
#rev      = 'feature/avoid-errors'
on_cmd   = ['Denite', 'DeniteBufferDir', 'DeniteCursorWord']
on_func  = ['denite#']
depends  = ['dwm.vim']
hook_add = '''"{{{
  noremap zn :<C-u>DeniteBufferDir my_file my_file:new<CR>
  noremap zN :<C-u>Denite my_file<CR>
  noremap zl :<C-u>Denite outline<CR>
  noremap zL :<C-u>Denite decls<CR>
  noremap za :<C-u>Denite file_rec<CR>
  noremap zg :<C-u>Denite grep<CR>
  noremap zi :<C-u>Denite gitlog<CR>
  noremap zI :<C-u>Denite gitlog:all<CR>
  noremap z/ :<C-u>DeniteCursorWord grep:.<CR>
  noremap zd :<C-u>Denite -default-action=narrow dein<CR>
  noremap zD :<C-u>Denite dein_log<CR>
  noremap zp :<C-u>Denite my_buffer my_file_mru<CR>
  noremap zh :<C-u>Denite ghq<CR>
  noremap zm :<C-u>Denite memo memo:new<CR>
  noremap ze :<C-u>Denite memo/grep::!<CR>
  noremap zU :<C-u>Denite -resume<CR>
  noremap zj :<C-u>Denite -resume -cursor-pos=+1 -immediately<CR>
  noremap zk :<C-u>Denite -resume -cursor-pos=-1 -immediately<CR>
  if has('nvim')
    tnoremap úð <C-\><C-n>:<C-u>Denite my_buffer my_file_mru<CR>
    tnoremap úî <C-\><C-n>:<C-u>call delphinus#denite#with_pwd('my_file')<CR>
    tnoremap úç <C-\><C-n>:<C-u>call delphinus#denite#with_pwd('grep')<CR>
    noremap úð :<C-u>Denite my_buffer my_file_mru<CR>
    noremap úî :<C-u>call delphinus#denite#with_pwd('my_file')<CR>
    noremap úç :<C-u>call delphinus#denite#with_pwd('grep')<CR>
  else
    tnoremap <A-z><A-p> <C-\><C-n>:<C-u>Denite my_buffer my_file_mru<CR>
    tnoremap <A-z><A-n> <C-\><C-n>:<C-u>call delphinus#denite#with_pwd('my_file')<CR>
    tnoremap <A-z><A-g> <C-\><C-n>:<C-u>call delphinus#denite#with_pwd('grep')<CR>
    noremap <A-z><A-p> :<C-u>Denite my_buffer my_file_mru<CR>
    noremap <A-z><A-n> :<C-u>call delphinus#denite#with_pwd('my_file')<CR>
    noremap <A-z><A-g> :<C-u>call delphinus#denite#with_pwd('grep')<CR>
  endif
"}}}'''
hook_source = 'call delphinus#init#denite#hook_source()'

[[plugins]]
repo      = 'Shougo/neomru.vim'
on_source = ['denite.nvim']

[[plugins]]
repo      = 'Jagua/vim-denite-ghq'
on_source = ['denite.nvim']

[[plugins]]
repo      = 'delphinus/my-denite-sources'
on_source = ['denite.nvim']

[[plugins]]
repo      = 'neoclide/denite-git'
on_source = ['denite.nvim', 'my-denite-sources']
depends   = ['vim-easygit']

[[plugins]]
repo = 'neoclide/vim-easygit'
