[[plugins]]
repo     = 'Shougo/denite.nvim'
on_cmd   = ['Denite', 'DeniteBufferDir', 'DeniteCursorWord']
on_func  = ['denite#']
depends  = ['dwm.vim', 'fruzzy']
hook_add = ''' "{{{
  if has('nvim')
    autocmd BufEnter \[denite\] call s:denite_change_cursorline()
    function! s:denite_change_cursorline() abort
      let output = execute('hi Cursorline')
      let guibg = matchstr(output, '\(guibg=\)\@<=#[a-zA-Z0-9]\+')
      hi CursorLine guibg=#183203
      execute 'autocmd BufLeave <buffer> hi Cursorline guibg=' . guibg
    endfunction
  endif

  function! s:my_denite_outline(filetype) abort
    execute 'Denite' a:filetype ==# 'go' ? "decls:'%:p'" : 'outline'
  endfunction

  function! s:my_denite_decls(filetype) abort
    if a:filetype ==# 'go'
      Denite decls
    else
      call denite#util#print_error('decls does not support filetypes except go')
    endif
  endfunction

  function! s:my_denite_file_rec_goroot() abort
    if !executable('go')
      call denite#util#print_error('`go` executable not found')
      return
    endif
    let out = system('go env | grep ''^GOROOT='' | cut -d\" -f2')
    let goroot = substitute(out, '\n', '', '')
    call denite#start(
          \ [{'name': 'my_file_rec', 'args': [goroot]}],
          \ {'input': '.go'})
  endfunction

  function! s:my_denite_with_pwd(action) abort
    let pwd = get(b:, '__pwd__', '')
    if a:action ==# 'grep'
      call denite#start([{'name': 'grep', 'args': [pwd, '', '!']}])
    elseif a:action ==# 'my_file_rec'
      call denite#start([{'name': 'my_file_rec', 'args': [pwd]}])
    else
      call denite#start([{'name': a:action, 'args': ['', pwd]}])
    endif
  endfunction

  noremap zn :<C-u>DeniteBufferDir -expand my_file my_file:new<CR>
  noremap zN :<C-u>Denite npm<CR>
  noremap zl :<C-u>call <SID>my_denite_outline(&filetype)<CR>
  noremap zL :<C-u>call <SID>my_denite_decls(&filetype)<CR>
  noremap za :<C-u>Denite -expand my_file_rec<CR>
  noremap zg :<C-u>Denite -max-dynamic-update-candidates=0 grep<CR>
  noremap zG :<C-u>execute 'Denite grep:' . expand('%:h') . '::!'<CR>
  noremap zi :<C-u>Denite gitlog<CR>
  noremap zI :<C-u>Denite gitlog:all<CR>
  noremap z/ :<C-u>DeniteCursorWord grep:.<CR>
  noremap zd :<C-u>Denite -buffer-name=denite-z z<CR>
  noremap zD :<C-u>Denite dein/log<CR>
  noremap zp :<C-u>Denite -expand my_buffer my_file_old<CR>
  noremap zh :<C-u>Denite ghq<CR>
  noremap zm :<C-u>Denite memo memo:new<CR>
  noremap ze :<C-u>Denite memo/grep::!<CR>
  noremap zU :<C-u>Denite -resume<CR>
  noremap zj :<C-u>Denite -resume -cursor-pos=+1 -immediately<CR>
  noremap zk :<C-u>Denite -resume -cursor-pos=-1 -immediately<CR>
  noremap zT :<C-u>call <SID>my_denite_file_rec_goroot()<CR>
  noremap zZ :<C-u>Denite buffer -input=term:// -immediately<CR>
  noremap zy :<C-u>Denite yankround<CR>
  noremap zY :<C-u>Denite -default-action=delete yankround<CR>
  noremap zS :<C-u>Denite scriptnames<CR>
  tnoremap úá         <C-\><C-n>:<C-u>call <SID>my_denite_with_pwd('my_file_rec')<CR>
  tnoremap Ωå         <C-\><C-n>:<C-u>call <SID>my_denite_with_pwd('my_file_rec')<CR>
  tnoremap <A-z><A-a> <C-\><C-n>:<C-u>call <SID>my_denite_with_pwd('my_file_rec')<CR>
  tnoremap Ω˜         <C-\><C-n>:<C-u>call <SID>my_denite_with_pwd('my_file')<CR>
  tnoremap úî         <C-\><C-n>:<C-u>call <SID>my_denite_with_pwd('my_file')<CR>
  tnoremap <A-z><A-n> <C-\><C-n>:<C-u>call <SID>my_denite_with_pwd('my_file')<CR>
  tnoremap Ω©         <C-\><C-n>:<C-u>call <SID>my_denite_with_pwd('grep')<CR>
  tnoremap úç         <C-\><C-n>:<C-u>call <SID>my_denite_with_pwd('grep')<CR>
  tnoremap <A-z><A-g> <C-\><C-n>:<C-u>call <SID>my_denite_with_pwd('grep')<CR>
  nnoremap Ωπ         :<C-u>Denite -expand my_buffer my_file_old<CR>
  nnoremap úð         :<C-u>Denite -expand my_buffer my_file_old<CR>
  nnoremap <A-z><A-p> :<C-u>Denite -expand my_buffer my_file_old<CR>
  nnoremap Ω˜         :<C-u>call <SID>my_denite_with_pwd('my_file')<CR>
  nnoremap úî         :<C-u>call <SID>my_denite_with_pwd('my_file')<CR>
  nnoremap <A-z><A-n> :<C-u>call <SID>my_denite_with_pwd('my_file')<CR>
  nnoremap Ω©         :<C-u>call <SID>my_denite_with_pwd('grep')<CR>
  nnoremap úç         :<C-u>call <SID>my_denite_with_pwd('grep')<CR>
  nnoremap <A-z><A-g> :<C-u>call <SID>my_denite_with_pwd('grep')<CR>
  nnoremap #  :<C-u>Denite line<CR>
  nnoremap g# :<C-u>Denite line:buffers<CR>
"}}} '''
hook_post_source = ''' "{{{
  function! s:dwm_new(context)
    call DWM_New()
    call denite#do_action(a:context, 'open', a:context['targets'])
  endfunction

  " from doc
  function! s:candidate_file_rec(context) abort
    let path = a:context['targets'][0]['action__path']
    let dir = denite#util#path2directory(path)
    let sources_queue = a:context['sources_queue'] + [[
          \ {'name': 'my_file_rec', 'args': [dir]},
          \ ]]
    return {'sources_queue': sources_queue}
  endfunction

  function! s:candidate_grep(context) abort
    let path = a:context['targets'][0]['action__path']
    let dir = denite#util#path2directory(path)
    let sources_queue = a:context['sources_queue'] + [[
          \ {'name': 'grep', 'args': [path, '', '!']},
          \ ]]
    return {'is_interactive': v:false, 'sources_queue': sources_queue}
  endfunction

  function! s:narrow_grep(context, ...) abort
    let sources = get(a:context, 'sources', [])
    let filtered = filter(copy(sources),
          \ {i, v -> get(v, 'name', '') ==# 'grep'})
    if len(filtered) == 0
      call denite#util#print_error('current sources does not include `grep`.')
      return
    endif
    let args = get(filtered[0], 'args', [])
    " TODO: add feature to know is_interactive in context
    "let pattern = get(args, 2, '')
    "if pattern !=# '!'
      "call denite#util#print_error('current grep source is not interactive')
      "return
    "endif
    let path = get(args, 0, '')
    let opt = get(args, 1, '')
    let input = get(a:context, 'input', '')
    let pattern = substitute(input, '\s\+', '.*', 'g')
    let sources_queue = a:context['sources_queue'] + [[
          \ {'name': 'grep', 'args': [path, opt, pattern]},
          \ ]]
    return {'sources_queue': sources_queue}
  endfunction

  " Use pt for grepping files
  call denite#custom#var('grep', 'command', ['pt'])
  call denite#custom#var('grep', 'default_opts',
        \ ['--nogroup', '--nocolor', '--smart-case', '--ignore=.git', '--ignore=dist', '--ignore=node_modules'])
  call denite#custom#var('grep', 'recursive_opts', [])
  call denite#custom#var('grep', 'pattern_opt', [])
  call denite#custom#var('grep', 'separator', ['--'])
  call denite#custom#var('grep', 'final_opts', [])

  " Use fd for finding files
  call denite#custom#var('my_file_rec', 'command',
        \ ['fd', '--follow', '--hidden', '--exclude', '.git', '.*'])

  call denite#custom#action('buffer,directory,file,memo,openable', 'dwm_new', function('s:dwm_new'))
  call denite#custom#action('buffer,directory,file,openable', 'my_file_rec', function('s:candidate_file_rec'))
  call denite#custom#action('buffer,directory,file,openable', 'grep', function('s:candidate_grep'))
  call denite#custom#action('file', 'grep', function('s:narrow_grep'))

  call denite#custom#source('grep', 'args', ['', '', '!'])
  call denite#custom#source('grep', 'converters', ['converter/abbr_word'])

  " ref. https://github.com/arcticicestudio/nord-vim/issues/79
  call denite#custom#option('_', {
        \ 'cached_filter': v:true,
        \ 'cursor_shape': v:true,
        \ 'cursor_wrap': v:true,
        \ 'highlight_filter_background': 'DeniteFilter',
        \ 'highlight_matched_char': 'Underlined',
        \ 'matchers': 'matcher/fruzzy',
        \ 'prompt': '$ ',
        \ 'split': 'floating',
        \ 'start_filter': v:true,
        \ 'statusline': v:false,
        \ })

  function! s:denite_detect_size() abort
    let s:denite_winheight = 20
    let s:denite_winrow = &lines > s:denite_winheight ? (&lines - s:denite_winheight) / 2 : 0
    let s:denite_winwidth = &columns > 240 ? &columns / 2 : 120
    let s:denite_wincol = &columns > s:denite_winwidth ? (&columns - s:denite_winwidth) / 2 : 0
    call denite#custom#option('_', {
          \ 'wincol': s:denite_wincol,
          \ 'winheight': s:denite_winheight,
          \ 'winrow': s:denite_winrow,
          \ 'winwidth': s:denite_winwidth,
          \ })
  endfunction

  augroup denite-detect-size
    autocmd!
    autocmd VimResized * call <SID>denite_detect_size()
  augroup END

  call s:denite_detect_size()

  call denite#custom#option('denite-z', 'default_action', 'narrow')
"}}} '''

[plugins.ftplugin]
denite = ''' "{{{
  let b:dwm_disabled = 1
  let b:auto_cursorline_disabled = 1
  nnoremap <silent><buffer> <C-j> j
  nnoremap <silent><buffer> <C-k> k
  nnoremap <silent><buffer><expr> <BS>    denite#do_map('move_up_path')
  nnoremap <silent><buffer><expr> <C-a>   denite#do_map('do_action', 'my_file_rec')
  nnoremap <silent><buffer><expr> <C-c>   denite#do_map('quit')
  nnoremap <silent><buffer><expr> <C-g>   denite#do_map('do_action', 'grep')
  nnoremap <silent><buffer><expr> <C-n>   denite#do_map('do_action', 'dwm_new')
  nnoremap <silent><buffer><expr> <C-x>   denite#do_map('do_action', 'quick_move')
  nnoremap <silent><buffer><expr> <CR>    denite#do_map('do_action')
  nnoremap <silent><buffer><expr> <Space> denite#do_map('toggle_select).'j'
  nnoremap <silent><buffer><expr> <Tab>   denite#do_map('choose_action')
  nnoremap <silent><buffer><expr> a       denite#do_map('open_filter_buffer')
  nnoremap <silent><buffer><expr> i       denite#do_map('open_filter_buffer')
  nnoremap <silent><buffer><expr> p       denite#do_map('do_action', 'preview')
  nnoremap <silent><buffer><expr> q       denite#do_map('quit')
"}}} '''
denite-filter = ''' "{{{
  let b:dwm_disabled = 1
  let b:auto_cursorline_disabled = 1
  inoremap <silent><buffer><expr> <BS>    denite#do_map('move_up_path')
  inoremap <silent><buffer><expr> <C-c>   denite#do_map('quit')
  nnoremap <silent><buffer><expr> <C-c>   denite#do_map('quit')

  " These mappings are not recommended in doc.
  inoremap <silent><buffer> <C-j>   <Esc><C-w>p:call cursor(line('.')+1,0)<CR><C-w>pA
  inoremap <silent><buffer> <C-k>   <Esc><C-w>p:call cursor(line('.')-1,0)<CR><C-w>pA
"}}} '''

[[plugins]]
repo      = 'Jagua/vim-denite-ghq'
on_source = ['denite.nvim']

[[plugins]]
repo      = 'delphinus/my-denite-sources'
on_source = ['denite.nvim']

[[plugins]]
repo      = 'delphinus/vim-denite-scriptnames'
on_source = ['denite.nvim']

[[plugins]]
repo      = 'neoclide/denite-git'
on_source = ['denite.nvim', 'my-denite-sources']
depends   = ['vim-easygit']

[[plugins]]
repo      = 'neoclide/npm.nvim'
on_source = ['denite.nvim']
hook_source = '''
  let npm_py = 'rplugin/python3/denite/kind/npm.py'
  let npm_nvim_npm_py = g:dein#plugin.path . '/' . npm_py
  let denite = g:dein#_plugins['denite.nvim'].path
  let denite_npm_py = denite . '/' . npm_py
  if !filereadable(denite_npm_py)
    execute '!cp ' . npm_nvim_npm_py . ' ' . denite_npm_py
  endif
'''
hook_post_update = '''
  !npm install
'''

[[plugins]]
repo = 'neoclide/vim-easygit'

[[plugins]]
repo      = 'raghur/fruzzy'
on_source = ['denite.nvim']
hook_add  = ''' "{{{
  let g:fruzzy#usenative = 1
  let g:fruzzy#sortonempty = 0
"}}} '''
hook_post_update = 'call fruzzy#install()'

[[plugins]]
repo      = 'rafi/vim-denite-z'
on_source = ['denite.nvim']
