[[plugins]]
repo = 'zchee/deoplete-zsh'

[[plugins]]
repo    = 'zchee/deoplete-jedi'
depends = ['jedi-vim']

[[plugins]]
repo = 'SevereOverfl0w/deoplete-github'

[[plugins]]
repo = 'fishbullet/deoplete-ruby'

[[plugins]]
repo = 'roxma/nvim-yarp'
hook_source = '''
  " Set path for python3 for python36u packages in CentOS7
  if !executable('python3') && executable('python3.6')
    let g:python3_host_prog = exepath('python3.6')
  endif
'''

[[plugins]]
repo = 'roxma/vim-hug-neovim-rpc'

[[plugins]]
repo     = 'ujihisa/neco-look'
hook_add = '''"{{{
  let g:neocomplete#text_mode_filetypes = {
        \ 'rst': 1,
        \ 'markdown': 1,
        \ 'howm_memo': 1,
        \ 'howm_memo.markdown': 1,
        \ 'gitrebase': 1,
        \ 'gitcommit': 1,
        \ 'vcs-commit': 1,
        \ 'hybrid': 1,
        \ 'text': 1,
        \ 'help': 1,
        \ 'tex': 1,
        \ }
"}}}'''
